# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: CI

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  test-full:
    runs-on: [ubuntu-latest]

    steps:
      - name:
        uses: actions/checkout@v3
      
      - name: Set up Python 3.10.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"

      - name: Install dependencies
        run: python -m pip install ".[test]"
       
      - name: Test with pytest
        run: python -m pytest

  linter_name:
    name: Run Black formatter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Black formatter
        uses: rickstaa/action-black@v1
        with:
          black_args: ". --check"
